-- Ejecutar en Supabase → SQL Editor
create table public.pendientes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  "isCompleted" boolean not null default false
);

-- Igual que en la presentación: deshabilitar RLS para acceder desde el front
alter table public.pendientes disable row level security;
